let state={};const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
async function init(){const r=await fetch('/api/content',{cache:'no-store'});state=await r.json();$$('[data-key]').forEach(x=>x.value=state[x.dataset.key]||'');$$('[data-list]').forEach(x=>x.value=(state[x.dataset.list]||[]).join('\n'));renderGallery();renderColors();bindUploads();preview();applyColorPreview()}
function renderColors(){const b=$('#colors');b.innerHTML='';const names={navy:'Azul principal',gold:'Dorado',cream:'Crema',paper:'Fondo claro',ink:'Texto',sage:'Verde suave'};Object.entries(state.colors||{}).forEach(([k,v])=>{const safe=/^#[0-9a-f]{6}$/i.test(v)?v:'#000000';const d=document.createElement('div');d.className='color-control';d.innerHTML=`<div class="color-header"><span>${names[k]||k}</span><span class="color-dot" data-dot="${k}" style="background:${safe}"></span></div><div class="color-fields"><input class="color-picker" type="color" data-color="${k}" value="${safe}"><input class="color-hex" data-color-text="${k}" value="${safe}" maxlength="7"></div>`;b.appendChild(d)});$$('[data-color]').forEach(i=>i.oninput=e=>{const k=e.target.dataset.color,v=e.target.value;state.colors[k]=v;const t=$(`[data-color-text="${k}"]`),dot=$(`[data-dot="${k}"]`);if(t)t.value=v;if(dot)dot.style.background=v;applyColorPreview()});$$('[data-color-text]').forEach(i=>{i.oninput=e=>{const k=e.target.dataset.colorText;let v=e.target.value.trim();if(v&&!v.startsWith('#'))v='#'+v;if(/^#[0-9a-f]{6}$/i.test(v)){state.colors[k]=v;const p=$(`[data-color="${k}"]`),dot=$(`[data-dot="${k}"]`);if(p)p.value=v;if(dot)dot.style.background=v;e.target.classList.remove('invalid');applyColorPreview()}else e.target.classList.add('invalid')};i.onblur=e=>{const k=e.target.dataset.colorText;e.target.value=state.colors[k]||'#000000';e.target.classList.remove('invalid')}})}
function applyColorPreview(){Object.entries(state.colors||{}).forEach(([k,v])=>document.documentElement.style.setProperty('--'+k,v))}
function renderGallery(){const b=$('#galleryEditor');b.innerHTML='';(state.gallery||[]).forEach((g,i)=>{const d=document.createElement('div');d.className='gallery-row';d.innerHTML=`<label>Imagen / URL<input data-gsrc="${i}" value="${attr(g.src||'')}"><input type="file" data-gupload="${i}" accept=".png,.jpg,.jpeg,.webp,image/png,image/jpeg,image/webp"></label><label>Nombre<input data-galt="${i}" value="${attr(g.alt||'')}"></label><button class="danger" data-del="${i}">Eliminar</button>`;b.appendChild(d)});$$('[data-gsrc]').forEach(x=>x.oninput=e=>state.gallery[+e.target.dataset.gsrc].src=e.target.value);$$('[data-galt]').forEach(x=>x.oninput=e=>state.gallery[+e.target.dataset.galt].alt=e.target.value);$$('[data-gupload]').forEach(x=>x.onchange=async e=>{const f=e.target.files[0];if(!f)return;state.gallery[+e.target.dataset.gupload].src=await imageData(f);renderGallery()});$$('[data-del]').forEach(x=>x.onclick=e=>{state.gallery.splice(+e.target.dataset.del,1);renderGallery()})}
function bindUploads(){$$('[data-upload]').forEach(x=>x.onchange=async e=>{const f=e.target.files[0];if(!f)return;const k=e.target.dataset.upload;state[k]=await imageData(f);const t=$(`[data-key="${k}"]`);if(t)t.value=state[k];preview()})}
function imageData(file){return new Promise((res,rej)=>{if(!['image/png','image/jpeg','image/webp'].includes(file.type))return rej(new Error('Usa PNG, JPG/JPEG o WEBP'));const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{let w=im.width,h=im.height,s=Math.min(1,1600/Math.max(w,h));w=Math.round(w*s);h=Math.round(h*s);const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');if(file.type==='image/jpeg'){ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h)}ctx.drawImage(im,0,0,w,h);res(c.toDataURL(file.type==='image/png'?'image/png':file.type,.84))};im.onerror=()=>rej(new Error('Imagen inválida'));im.src=r.result};r.onerror=rej;r.readAsDataURL(file)})}
function preview(){if($('#preview-logo'))$('#preview-logo').src=state.logo||'';if($('#preview-heroImage'))$('#preview-heroImage').src=state.heroImage||''}
function collect(){$$('[data-key]').forEach(x=>state[x.dataset.key]=x.value);$$('[data-list]').forEach(x=>state[x.dataset.list]=x.value.split('\n').map(v=>v.trim()).filter(Boolean))}
function attr(s){return String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;')}
function status(m,ok){const s=$('#status');s.textContent=m;s.className=ok?'ok':'bad'}
$('#addGallery').onclick=()=>{state.gallery=state.gallery||[];state.gallery.push({src:'',alt:'Nueva imagen'});renderGallery()}
$('#saveBtn').onclick=async()=>{collect();status('Guardando...',true);try{const r=await fetch('/api/content',{method:'POST',headers:{'content-type':'application/json','x-admin-password':$('#password').value},body:JSON.stringify(state)});const j=await r.json();if(!r.ok)throw new Error(j.error||'No se pudo guardar');status('Cambios guardados correctamente.',true)}catch(e){status(e.message,false)}}
init();